Repository Archi999999/coinMarket, pull requests merged in 2024-01, with the labels that each got.

#38 Feat/loader
  package.json
  src/features/diagram/Diagram.tsx
  src/features/loader/HeaderContentLoader.tsx
  src/features/loader/OneCoinContentLoader.tsx
  src/features/loader/TableContentLoader.tsx
  src/features/loader/loaders.module.scss
  src/features/showWalletModal/showWalletModal.module.scss
  src/features/showWalletModal/showWalletModal.tsx
  src/pages/allCoins/AllCoins.tsx
  src/pages/oneCoin/OneCoin.tsx
  src/shared/ui/loader/Loader.tsx
  src/styles/_boilerplate.scss
  src/widgets/coinsTable/coinRow/CoinRow.tsx
  src/widgets/coinsTable/coinsTable/CoinsTable.tsx
  src/widgets/header/ui/Header.module.scss
  src/widgets/header/ui/Header.tsx
Labels: refactor, feature

#37 feat: add 404 page
  src/app/router.tsx
  src/assets/icons/ErrorImage.tsx
  src/pages/404/ErrorPage.module.scss
Labels: feature

#47 refactor: function abbreviateNumber
  src/features/showWalletModal/showWalletModal.tsx
  src/shared/utils/abbreviateNumber.ts
Labels: refactor
